#!/usr/bin/env bash
set -Eeuo pipefail

ENV_FILE="${MCP_ENV_FILE:-/etc/mcp-compute.env}"

if [[ ${EUID} -ne 0 ]]; then
  printf 'Run as root: sudo %s\n' "$0" >&2
  exit 1
fi

if [[ ! -r ${ENV_FILE} ]]; then
  printf 'Token file not found: %s\n' "${ENV_FILE}" >&2
  exit 1
fi

(
  # The file is root-owned and generated by install.sh.
  # shellcheck disable=SC1090
  . "${ENV_FILE}"
  if [[ -z ${MCP_TOKEN:-} ]]; then
    printf 'MCP_TOKEN is missing in %s\n' "${ENV_FILE}" >&2
    exit 1
  fi
  printf '%s\n' "${MCP_TOKEN}"
)
